---
global:
  pattern: ansible-edge-gitops

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

cloudInit:
  defaultUser: 'cloud-user'
  defaultPassword: '6toh-n1d5-9xpq'

vmNamespace: edge-gitops-vms

vms:
  kiosk:
    count: 2
    flavor: medium
    workload: desktop
    os: rhel8
    role: kiosk
    storage: 30Gi
    memory: 4Gi
    cores: 1
    sockets: 1
    threads: 1
    cloudInitUser: cloud-user
    cloudInitPassword: 6toh-n1d5-9xpq
    template: rhel8-desktop-medium
    sshsecret: secret/data/hub/kiosk-ssh
    sshpubkeyfield: publickey
    ports:
      - name: ssh
        port: 22
        protocol: TCP
        targetPort: 22
      - name: rdp
        port: 3389
        protocol: TCP
        targetPort: 3389
