odf:
  namespace: openshift-storage
  mon:
    requests:
       cpu: 1
       memory: 2Gi
  mds:
    requests:
      cpu: 3
      memory: 8Gi
  mgr:
    requests:
      cpu: 1
      memory: 3Gi
  noobaacore:
    requests:
      cpu: 1
      memory: 4Gi
  noobaadb:
    requests:
      cpu: 1
      memory: 4Gi
  osd:
    requests:
      cpu: 2
      memory: 5Gi
    pvc:
      storage: 2Ti
  storageClass:
    name: ocs-storagecluster-ceph-rgw
    objectStoreName: ocs-storagecluster-cephobjectstore

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

rbac:
  createRBAC: true
  createRoleBinding: true
  roles: [ ]
  serviceAccount:
    name: odf-sa
    namespace: openshift-cnv

toolbox:
  name: ocsinit
  enableCephTools: true

#Define the odf storageSystem parameters
storageSystem:
  deploy: true
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
  spec:
    kind: storagecluster.ocs.openshift.io/v1
    name: ocs-storagecluster
    namespace: ""

# Default to AWS storage class until others provide metal nodes
global:
  hub:
    storageClassName: gp2
