clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
  - vault
  - golang-external-secrets
  - ansible-automation-platform
  - cnv

  subscriptions:
    - name: ansible-automation-platform-operator
      namespace: ansible-automation-platform
      channel: stable-2.1
      csv: aap-operator.v2.1.0-0.1639138915

  projects:
  - hub
  - golang-external-secrets
  - ansible-automation-platform

  applications:
  - name: ansible-automation-platform
    project: ansible-automation-platform
    path: charts/hub/ansible-automation-platform

  - name: vault
    namespace: vault
    project: hub
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: v0.19.0
    overrides:
    - name: global.openshift
      value: "true"
    - name: injector.enabled
      value: "false"
    - name: ui.enabled
      value: "true"
    - name: ui.serviceType
      value: LoadBalancer
    - name: server.route.enabled
      value: "true"
    - name: server.route.host
      value: null
    - name: server.route.tls.termination
      value: edge
    - name: server.image.repository
      value: "registry.connect.redhat.com/hashicorp/vault"
    - name: server.image.tag
      value: "1.9.2-ubi"

  - name: golang-external-secrets
    namespace: golang-external-secrets
    project: golang-external-secrets
    path: charts/hub/golang-external-secrets

  - name: container-native-virtualization
    namespace: cnv
    project: hub
    path: charts/hub/cnv

  # Only the hub cluster here - managed entities are edge nodes
  managedClusterGroups: []
