clusterGroup:
  name: hub
  isHubCluster: true
  insecureUnsealVaultInsideCluster: true

  namespaces:
  - vault
  - golang-external-secrets
  - ansible-automation-platform
  - openshift-cnv
  - openshift-storage
  - edge-gitops-vms

  subscriptions:
    aap-operator:
      name: ansible-automation-platform-operator
      namespace: ansible-automation-platform
      channel: stable-2.2
      csv: aap-operator.v2.2.0-0.1653444770

    openshift-virtualization:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      channel: stable
      csv: kubevirt-hyperconverged-operator.v4.10.0

    openshift-data-foundation:
      name: odf-operator
      namespace: openshift-storage
      channel: stable-4.9
      csv: odf-operator.v4.9.5

  projects:
  - hub

  imperative:
    jobs:
      - name: deploy-kubevirt-worker
        playbook: ansible/deploy_kubevirt_worker.yml
        verbosity: "-vvv"
      - name: configure-aap-controller
        playbook: ansible/imperative_configure_controller.yml
        image: quay.io/hybridcloudpatterns/ansible-edge-gitops-ee:latest
        verbosity: "-vvv"
        timeout: "900"
    clusterRoleYaml:
      - apiGroups:
          - '*'
        resources:
          - 'machinesets'
        verbs:
          - '*'
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs:
          - get
          - list
          - watch


  applications:
    aap:
      name: ansible-automation-platform
      project: hub
      path: charts/hub/ansible-automation-platform

    aap:
      name: aap-config
      project: hub
      path: charts/hub/aap-config

    vault:
      name: vault
      namespace: vault
      project: hub
      chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: v0.20.1
      overrides:
      - name: global.openshift
        value: "true"
      - name: injector.enabled
        value: "false"
      - name: ui.enabled
        value: "true"
      - name: ui.serviceType
        value: LoadBalancer
      - name: server.route.enabled
        value: "true"
      - name: server.route.host
        value: null
      - name: server.route.tls.termination
        value: edge
      - name: server.image.repository
        value: "registry.connect.redhat.com/hashicorp/vault"
      - name: server.image.tag
        value: "1.10.3-ubi"

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets

    openshit-cnv:
      name: openshift-cnv
      namespace: openshift-cnv
      project: hub
      path: charts/hub/cnv

    odf:
      name: odf
      namespace: openshift-storage
      project: hub
      path: charts/hub/odf

    edge-gitops-vms:
      name: edge-gitops-vms
      namespace: edge-gitops-vms
      project: hub
      path: charts/hub/edge-gitops-vms

  # Only the hub cluster here - managed entities are edge nodes
  managedClusterGroups: []
