apiVersion: v1
items:
- apiVersion: kubevirt.io/v1
  kind: VirtualMachine
  metadata:
    annotations:
      vm.kubevirt.io/validations: |
        [
          {
            "name": "minimal-required-memory",
            "path": "jsonpath::.spec.domain.resources.requests.memory",
            "rule": "integer",
            "message": "This VM requires more memory.",
            "min": 1610612736
          }
        ]
    labels:
      app: rhel8-kiosk-02
      edge-gitops-role: kiosk
      vm.kubevirt.io/template: rhel8-desktop-medium
      vm.kubevirt.io/template.revision: "1"
      vm.kubevirt.io/template.version: v0.19.4
    name: rhel8-kiosk-02
  spec:
    dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: rhel8-kiosk-02
      spec:
        sourceRef:
          kind: DataSource
          name: rhel8
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
    running: true
    template:
      metadata:
        annotations:
          vm.kubevirt.io/flavor: medium
          vm.kubevirt.io/os: rhel8
          vm.kubevirt.io/workload: desktop
        labels:
          kubevirt.io/domain: rhel8-kiosk-02
          kubevirt.io/size: medium
          vm.kubevirt.io/name: rhel8-kiosk-02
      spec:
        domain:
          cpu:
            cores: 1
            sockets: 1
            threads: 1
          devices:
            disks:
            - disk:
                bus: virtio
              name: rhel8-kiosk-02
            - disk:
                bus: virtio
              name: cloudinitdisk
            inputs:
            - bus: virtio
              name: tablet
              type: tablet
            interfaces:
            - masquerade: {}
              name: default
            networkInterfaceMultiqueue: true
            rng: {}
          machine:
            type: pc-q35-rhel8.4.0
          resources:
            requests:
              memory: 4Gi
        evictionStrategy: LiveMigrate
        networks:
        - name: default
          pod: {}
        terminationGracePeriodSeconds: 180
        volumes:
        - dataVolume:
            name: rhel8-kiosk-02
          name: rhel8-kiosk-02
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: cloud-user
              password: s07a-wpul-vs6e
              chpasswd: { expire: False }
          name: cloudinitdisk
- apiVersion: v1
  kind: Service
  metadata:
    name: rhel8-kiosk-02-service
  spec:
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
    - name: rdp
      port: 3389
      protocol: TCP
      targetPort: 3389
    selector:
      vm.kubevirt.io/name: rhel8-kiosk-02
    sessionAffinity: None
    type: NodePort
kind: List
metadata: {}
