#!/usr/bin/env ansible-playbook
---
- name: "Retrieve Credentials for AAP on OpenShift"
  become: false
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
  tasks:
    - name: Retrieve API hostname for AAP
      kubernetes.core.k8s_info:
        kind: Route
        namespace: ansible-automation-platform
        name: controller
      register: aap_host
      until: aap_host.resources | length == 1
      retries: 20
      delay: 5

    - name: Set ansible_host
      set_fact:
        ansible_host: '{{ aap_host.resources[0].spec.host }}'

    - name: Retrieve admin password for AAP
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: ansible-automation-platform
        name: controller-admin-password
      register: admin_pw
      until: admin_pw.resources | length == 1
      retries: 20
      delay: 5

    - name: Set admin_password fact
      set_fact:
        admin_password: '{{ admin_pw.resources[0].data.password | b64decode }}'

    - name: Report AAP Endpoint
      debug:
        msg: 'AAP Endpoint: https://{{ ansible_host }}'

    - name: Report AAP User
      debug:
        msg: 'AAP Admin User: admin'

    - name: Report AAP Admin Password
      debug:
        msg: 'AAP Admin Password: {{ admin_password }}'

    - name: Retrieve manifest file
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: ansible-automation-platform
        name: aap-manifest
      register: manifest_secret
      until: manifest_secret.resources | length == 1
      retries: 20
      delay: 5

    - name: Set manifest fact
      ansible.builtin.set_fact:
        manifest_file: '{{ manifest_secret.resources[0].data.content | b64decode }}'

    - name: Retrieve rhsm secret
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: ansible-automation-platform
        name: rhsm
      register: rhsm_secret
      until: rhsm_secret.resources | length == 1
      retries: 20
      delay: 5

    - name: Retrieve kiosk-ssh secret
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: ansible-automation-platform
        name: kiosk-ssh
      register: kiosk_ssh_secret
      until: kiosk_ssh_secret.resources | length == 1
      retries: 20
      delay: 5

    - name: Retrieve kiosk-extra secret
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: ansible-automation-platform
        name: kiosk-extra
      register: kiosk_extra_secret
      until: kiosk_extra_secret.resources | length == 1
      retries: 20
      delay: 5
