---
- name: Get dynamic inventory
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    inventory_namespace: 'edge-gitops-vms'
    inventory_kind: 'Service'
    inventory_target_group: 'VMs'
  collections:
    - kubernetes.core
    - community.general

  tasks:
  - name: "Get {{ inventory_kind }}'s"
    kubernetes.core.k8s_info:
      api_version: v1
      kind: '{{ inventory_kind }}'
      namespace: '{{ inventory_namespace }}'
    register: nodes

  - name: Debug
    ansible.builtin.debug:
      msg: "{{ item }}.{{ inventory_namespace }}.svc"
    loop: "{{ nodes | community.general.json_query('resources[*].metadata.name') }}"

  - name: add hosts
    ansible.builtin.add_host:
      hostname: "{{ item }}.{{ inventory_namespace }}.svc"
      groups:
        - '{{ inventory_target_group }}'
    loop: "{{ nodes | community.general.json_query('resources[*].metadata.name') }}"
